/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "velox/experimental/cudf/expression/GeometryKernels.h"

#include <cudf/column/column_factories.hpp>
#include <cudf/null_mask.hpp>
#include <cudf/lists/lists_column_view.hpp>
#include <cudf/strings/strings_column_view.hpp>
#include <cudf/table/table_view.hpp>
#include <cudf/utilities/bit.hpp>
#include <cudf/utilities/error.hpp>

// cuSpatial's header-only algorithm API (see
// CMake/resolve_dependency_modules/cuspatial.cmake for why this is
// header-only rather than a linked libcuspatial dependency, and for the
// small compatibility shims required to build cuSpatial 25.08's headers
// against the cuDF 26.08-generation RMM/CCCL toolchain used elsewhere in
// this repo). These headers depend only on RMM/Thrust/CUDA, never on
// libcudf, so they are safe to mix with cuDF's own column APIs below.
//
// cuspatial_compat_fixups.cuh (generated by CMake/resolve_dependency_modules
// cuspatial.cmake) must be included before <cuspatial/distance.cuh>: it pulls
// cuspatial::detail::point_polygon_intersects into namespace cuspatial via a
// using-declaration, which pairwise_point_polygon_distance's unqualified call
// to it requires (see cuspatial.cmake for the full explanation).
#include <cuspatial_compat_fixups.cuh>

#include <cuspatial/distance.cuh>
#include <cuspatial/geometry/vec_2d.hpp>
#include <cuspatial/range/multipoint_range.cuh>
#include <cuspatial/range/multipolygon_range.cuh>

#include <rmm/device_uvector.hpp>
#include <rmm/exec_policy.hpp>

#include <thrust/for_each.h>
#include <thrust/iterator/counting_iterator.h>
#include <thrust/iterator/transform_iterator.h>
#include <thrust/scan.h>

#include <cmath>
#include <cstdint>
#include <cstring>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace facebook::velox::cudf_velox {
namespace {

// Must match GeometrySerializationType in GeometryConstants.h.
constexpr uint8_t kPointTag = 0;
constexpr uint8_t kLineStringTag = 2;
constexpr uint8_t kMultiLineStringTag = 3;
constexpr uint8_t kPolygonTag = 4;
constexpr uint8_t kEnvelopeTag = 7;
constexpr int32_t kPointBlobSize = 17; // 1 + 8 + 8
constexpr int32_t kEsriPolygon = 5;
constexpr int32_t kEsriPolyline = 3;
constexpr int32_t kEmptyPolygonBlobSize = 45; // tag+esri+envelope+numParts+numPoints
constexpr int32_t kEmptyLineStringBlobSize = 45;
constexpr uint32_t kWkbSridFlag = 0x20000000u;

__device__ inline int32_t veloxLineStringBlobSize(int32_t numPoints) {
  // tag + esri + envelope + numParts + numPoints + partStarts[1] + xy
  return kEmptyLineStringBlobSize + 4 + 16 * numPoints;
}

__device__ inline void markInvalid(int32_t* flag) {
  if (flag != nullptr) {
    atomicOr(flag, 1);
  }
}

__device__ inline bool readPointXY(
    char const* data,
    cudf::size_type len,
    double& x,
    double& y,
    int32_t* invalidTypeFlag) {
  if (len < kPointBlobSize ||
      static_cast<uint8_t>(data[0]) != kPointTag) {
    markInvalid(invalidTypeFlag);
    return false;
  }
  // Device memcpy of unaligned doubles from the geometry blob.
  char xb[8];
  char yb[8];
#pragma unroll
  for (int i = 0; i < 8; ++i) {
    xb[i] = data[1 + i];
    yb[i] = data[9 + i];
  }
  {
    double tmpX = 0;
    double tmpY = 0;
    auto* xp = reinterpret_cast<char*>(&tmpX);
    auto* yp = reinterpret_cast<char*>(&tmpY);
#pragma unroll
    for (int i = 0; i < 8; ++i) {
      xp[i] = xb[i];
      yp[i] = yb[i];
    }
    x = tmpX;
    y = tmpY;
  }
  return true;
}

__device__ inline bool isEmptyPoint(double x, double y) {
  return isnan(x) && isnan(y);
}

__device__ inline uint32_t readU32(char const* p, bool littleEndian) {
  uint8_t b0 = static_cast<uint8_t>(p[0]);
  uint8_t b1 = static_cast<uint8_t>(p[1]);
  uint8_t b2 = static_cast<uint8_t>(p[2]);
  uint8_t b3 = static_cast<uint8_t>(p[3]);
  if (littleEndian) {
    return uint32_t{b0} | (uint32_t{b1} << 8) | (uint32_t{b2} << 16) |
        (uint32_t{b3} << 24);
  }
  return uint32_t{b3} | (uint32_t{b2} << 8) | (uint32_t{b1} << 16) |
      (uint32_t{b0} << 24);
}

__device__ inline double readF64(char const* p, bool littleEndian) {
  char bytes[8];
  if (littleEndian) {
#pragma unroll
    for (int i = 0; i < 8; ++i) {
      bytes[i] = p[i];
    }
  } else {
#pragma unroll
    for (int i = 0; i < 8; ++i) {
      bytes[i] = p[7 - i];
    }
  }
  double out = 0;
  auto* outb = reinterpret_cast<char*>(&out);
#pragma unroll
  for (int i = 0; i < 8; ++i) {
    outb[i] = bytes[i];
  }
  return out;
}

__device__ inline double distPointSegment(
    double px,
    double py,
    double ax,
    double ay,
    double bx,
    double by) {
  double const dx = bx - ax;
  double const dy = by - ay;
  double const len2 = dx * dx + dy * dy;
  if (len2 == 0.0) {
    double const ex = px - ax;
    double const ey = py - ay;
    return sqrt(ex * ex + ey * ey);
  }
  double t = ((px - ax) * dx + (py - ay) * dy) / len2;
  t = fmin(1.0, fmax(0.0, t));
  double const qx = ax + t * dx;
  double const qy = ay + t * dy;
  double const ex = px - qx;
  double const ey = py - qy;
  return sqrt(ex * ex + ey * ey);
}

/// Even-odd point-in-ring. partStart/partEnd are point indices [start, end).
__device__ inline bool pointInRing(
    double px,
    double py,
    double const* xy,
    int32_t partStart,
    int32_t partEnd) {
  if (partEnd - partStart < 3) {
    return false;
  }
  bool inside = false;
  for (int32_t i = partStart, j = partEnd - 1; i < partEnd; j = i++) {
    double const xi = xy[2 * i];
    double const yi = xy[2 * i + 1];
    double const xj = xy[2 * j];
    double const yj = xy[2 * j + 1];
    bool const intersect = ((yi > py) != (yj > py)) &&
        (px < (xj - xi) * (py - yi) / (yj - yi + 0.0) + xi);
    if (intersect) {
      inside = !inside;
    }
  }
  return inside;
}

__device__ inline double minDistToRing(
    double px,
    double py,
    double const* xy,
    int32_t partStart,
    int32_t partEnd) {
  double best = INFINITY;
  if (partEnd - partStart < 2) {
    return best;
  }
  for (int32_t i = partStart; i < partEnd - 1; ++i) {
    double const d = distPointSegment(
        px,
        py,
        xy[2 * i],
        xy[2 * i + 1],
        xy[2 * (i + 1)],
        xy[2 * (i + 1) + 1]);
    best = fmin(best, d);
  }
  // Close the ring if first != last (still safe if already closed).
  int32_t const last = partEnd - 1;
  double const dClose = distPointSegment(
      px,
      py,
      xy[2 * last],
      xy[2 * last + 1],
      xy[2 * partStart],
      xy[2 * partStart + 1]);
  return fmin(best, dClose);
}

__device__ inline int32_t readI32Native(char const* p) {
  int32_t v = 0;
  auto* outb = reinterpret_cast<char*>(&v);
#pragma unroll
  for (int i = 0; i < 4; ++i) {
    outb[i] = p[i];
  }
  return v;
}

__device__ inline double readF64Native(char const* p) {
  double v = 0;
  auto* outb = reinterpret_cast<char*>(&v);
#pragma unroll
  for (int i = 0; i < 8; ++i) {
    outb[i] = p[i];
  }
  return v;
}

__device__ inline void writeI32Native(char* p, int32_t v) {
  auto const* b = reinterpret_cast<char const*>(&v);
#pragma unroll
  for (int i = 0; i < 4; ++i) {
    p[i] = b[i];
  }
}

__device__ inline void writeF64Native(char* p, double v) {
  auto const* b = reinterpret_cast<char const*>(&v);
#pragma unroll
  for (int i = 0; i < 8; ++i) {
    p[i] = b[i];
  }
}

__device__ inline double xyBytesX(char const* xy, int32_t i) {
  return readF64Native(xy + static_cast<std::size_t>(i) * 16);
}

__device__ inline double xyBytesY(char const* xy, int32_t i) {
  return readF64Native(xy + static_cast<std::size_t>(i) * 16 + 8);
}

__device__ inline bool pointInRingBytes(
    double px,
    double py,
    char const* xy,
    int32_t partStart,
    int32_t partEnd) {
  if (partEnd - partStart < 3) {
    return false;
  }
  bool inside = false;
  for (int32_t i = partStart, j = partEnd - 1; i < partEnd; j = i++) {
    double const xi = xyBytesX(xy, i);
    double const yi = xyBytesY(xy, i);
    double const xj = xyBytesX(xy, j);
    double const yj = xyBytesY(xy, j);
    bool const intersect = ((yi > py) != (yj > py)) &&
        (px < (xj - xi) * (py - yi) / (yj - yi + 0.0) + xi);
    if (intersect) {
      inside = !inside;
    }
  }
  return inside;
}

__device__ inline double minDistToRingBytes(
    double px,
    double py,
    char const* xy,
    int32_t partStart,
    int32_t partEnd) {
  double best = INFINITY;
  if (partEnd - partStart < 2) {
    return best;
  }
  for (int32_t i = partStart; i < partEnd - 1; ++i) {
    double const d = distPointSegment(
        px,
        py,
        xyBytesX(xy, i),
        xyBytesY(xy, i),
        xyBytesX(xy, i + 1),
        xyBytesY(xy, i + 1));
    best = fmin(best, d);
  }
  int32_t const last = partEnd - 1;
  double const dClose = distPointSegment(
      px,
      py,
      xyBytesX(xy, last),
      xyBytesY(xy, last),
      xyBytesX(xy, partStart),
      xyBytesY(xy, partStart));
  return fmin(best, dClose);
}

/// Distance from point to Velox POLYGON/ENVELOPE blob (unaligned-safe).
__device__ inline bool distPointToPolygonBlob(
    double px,
    double py,
    char const* data,
    cudf::size_type len,
    double& outDist,
    int32_t* invalidTypeFlag) {
  if (len < 1) {
    markInvalid(invalidTypeFlag);
    return false;
  }
  uint8_t const tag = static_cast<uint8_t>(data[0]);

  char envXy[80]; // 5 points * 16
  char const* xy = nullptr;
  int32_t numParts = 0;
  int32_t numPoints = 0;
  bool envelope = false;

  if (tag == kEnvelopeTag) {
    if (len < 1 + 32) {
      markInvalid(invalidTypeFlag);
      return false;
    }
    double const xmin = readF64Native(data + 1);
    double const ymin = readF64Native(data + 9);
    double const xmax = readF64Native(data + 17);
    double const ymax = readF64Native(data + 25);
    double coords[10] = {
        xmin,
        ymin,
        xmax,
        ymin,
        xmax,
        ymax,
        xmin,
        ymax,
        xmin,
        ymin};
#pragma unroll
    for (int i = 0; i < 10; ++i) {
      writeF64Native(envXy + i * 8, coords[i]);
    }
    xy = envXy;
    numParts = 1;
    numPoints = 5;
    envelope = true;
  } else if (tag == kPolygonTag) {
    if (len < kEmptyPolygonBlobSize) {
      markInvalid(invalidTypeFlag);
      return false;
    }
    numParts = readI32Native(data + 37);
    numPoints = readI32Native(data + 41);
    if (numParts <= 0 || numPoints <= 0) {
      return false; // empty → null
    }
    std::size_t const partsBytes =
        static_cast<std::size_t>(numParts) * sizeof(int32_t);
    std::size_t const xyBytesNeeded =
        static_cast<std::size_t>(numPoints) * 16;
    if (static_cast<std::size_t>(len) <
        static_cast<std::size_t>(kEmptyPolygonBlobSize) + partsBytes +
            xyBytesNeeded) {
      markInvalid(invalidTypeFlag);
      return false;
    }
    xy = data + kEmptyPolygonBlobSize +
        static_cast<std::size_t>(numParts) * 4;
  } else {
    markInvalid(invalidTypeFlag);
    return false;
  }

  // Compute part starts/ends without lambdas (device-friendly).
  int32_t shellStart = 0;
  int32_t shellEnd = numPoints;
  if (!envelope) {
    shellStart = readI32Native(data + kEmptyPolygonBlobSize);
    shellEnd = (numParts > 1)
        ? readI32Native(data + kEmptyPolygonBlobSize + 4)
        : numPoints;
  }

  bool const inShell =
      pointInRingBytes(px, py, xy, shellStart, shellEnd);
  bool inHole = false;
  if (inShell && !envelope) {
    for (int32_t p = 1; p < numParts; ++p) {
      int32_t const hs = readI32Native(
          data + kEmptyPolygonBlobSize + static_cast<std::size_t>(p) * 4);
      int32_t const he = (p + 1 < numParts)
          ? readI32Native(
                data + kEmptyPolygonBlobSize +
                static_cast<std::size_t>(p + 1) * 4)
          : numPoints;
      if (pointInRingBytes(px, py, xy, hs, he)) {
        inHole = true;
        break;
      }
    }
  }
  if (inShell && !inHole) {
    outDist = 0.0;
    return true;
  }

  double best = INFINITY;
  for (int32_t p = 0; p < numParts; ++p) {
    int32_t ps = 0;
    int32_t pe = numPoints;
    if (!envelope) {
      ps = readI32Native(
          data + kEmptyPolygonBlobSize + static_cast<std::size_t>(p) * 4);
      pe = (p + 1 < numParts)
          ? readI32Native(
                data + kEmptyPolygonBlobSize +
                static_cast<std::size_t>(p + 1) * 4)
          : numPoints;
    }
    best = fmin(best, minDistToRingBytes(px, py, xy, ps, pe));
  }
  outDist = best;
  return true;
}

__device__ inline int32_t veloxPolygonBlobSize(int32_t numParts, int32_t numPoints) {
  return kEmptyPolygonBlobSize + 4 * numParts + 16 * numPoints;
}

/// Inspect WKB and return Velox blob byte size. Returns false → null row.
__device__ inline bool wkbVeloxOutputSize(
    char const* wkb,
    cudf::size_type len,
    int32_t* outSize,
    int32_t* invalidTypeFlag) {
  if (len < 5) {
    markInvalid(invalidTypeFlag);
    return false;
  }
  uint8_t const byteOrder = static_cast<uint8_t>(wkb[0]);
  if (byteOrder > 1) {
    markInvalid(invalidTypeFlag);
    return false;
  }
  bool const le = byteOrder == 1;
  uint32_t typeWord = readU32(wkb + 1, le);
  bool const hasSrid = (typeWord & kWkbSridFlag) != 0;
  uint32_t const geomType = typeWord & 0xFFu;
  cudf::size_type body = 5;
  if (hasSrid) {
    if (len < 9) {
      markInvalid(invalidTypeFlag);
      return false;
    }
    body = 9;
  }

  if (geomType == 1) {
    if (len < body + 16) {
      markInvalid(invalidTypeFlag);
      return false;
    }
    *outSize = kPointBlobSize;
    return true;
  }
  if (geomType != 3) {
    markInvalid(invalidTypeFlag);
    return false;
  }
  // Polygon: numRings + rings.
  if (len < body + 4) {
    markInvalid(invalidTypeFlag);
    return false;
  }
  uint32_t const numRings = readU32(wkb + body, le);
  if (numRings > 100000u) {
    markInvalid(invalidTypeFlag);
    return false;
  }
  cudf::size_type off = body + 4;
  int32_t numPoints = 0;
  for (uint32_t r = 0; r < numRings; ++r) {
    if (off + 4 > len) {
      markInvalid(invalidTypeFlag);
      return false;
    }
    uint32_t const n = readU32(wkb + off, le);
    off += 4;
    if (n > 10000000u ||
        off + static_cast<cudf::size_type>(n) * 16 > len) {
      markInvalid(invalidTypeFlag);
      return false;
    }
    off += static_cast<cudf::size_type>(n) * 16;
    numPoints += static_cast<int32_t>(n);
  }
  int32_t const numParts = static_cast<int32_t>(numRings);
  *outSize = (numParts == 0) ? kEmptyPolygonBlobSize
                             : veloxPolygonBlobSize(numParts, numPoints);
  return true;
}

__device__ inline bool wkbToVeloxBlob(
    char const* wkb,
    cudf::size_type len,
    char* out,
    int32_t outSize,
    int32_t* invalidTypeFlag) {
  if (len < 5) {
    markInvalid(invalidTypeFlag);
    return false;
  }
  uint8_t const byteOrder = static_cast<uint8_t>(wkb[0]);
  if (byteOrder > 1) {
    markInvalid(invalidTypeFlag);
    return false;
  }
  bool const le = byteOrder == 1;
  uint32_t typeWord = readU32(wkb + 1, le);
  bool const hasSrid = (typeWord & kWkbSridFlag) != 0;
  uint32_t const geomType = typeWord & 0xFFu;
  cudf::size_type body = 5;
  if (hasSrid) {
    if (len < 9) {
      markInvalid(invalidTypeFlag);
      return false;
    }
    body = 9;
  }

  if (geomType == 1) {
    if (outSize < kPointBlobSize || len < body + 16) {
      markInvalid(invalidTypeFlag);
      return false;
    }
    double const x = readF64(wkb + body, le);
    double const y = readF64(wkb + body + 8, le);
    out[0] = static_cast<char>(kPointTag);
    writeF64Native(out + 1, x);
    writeF64Native(out + 9, y);
    return true;
  }
  if (geomType != 3) {
    markInvalid(invalidTypeFlag);
    return false;
  }
  if (len < body + 4) {
    markInvalid(invalidTypeFlag);
    return false;
  }
  uint32_t const numRings = readU32(wkb + body, le);
  int32_t const numParts = static_cast<int32_t>(numRings);
  if (numParts == 0) {
    if (outSize < kEmptyPolygonBlobSize) {
      markInvalid(invalidTypeFlag);
      return false;
    }
    out[0] = static_cast<char>(kPolygonTag);
    writeI32Native(out + 1, kEsriPolygon);
    double const nan = NAN;
    writeF64Native(out + 5, nan);
    writeF64Native(out + 13, nan);
    writeF64Native(out + 21, nan);
    writeF64Native(out + 29, nan);
    writeI32Native(out + 37, 0);
    writeI32Native(out + 41, 0);
    return true;
  }

  // Count points (already validated in size pass, re-check bounds).
  cudf::size_type off = body + 4;
  int32_t numPoints = 0;
  for (int32_t r = 0; r < numParts; ++r) {
    if (off + 4 > len) {
      markInvalid(invalidTypeFlag);
      return false;
    }
    uint32_t const n = readU32(wkb + off, le);
    off += 4 + static_cast<cudf::size_type>(n) * 16;
    numPoints += static_cast<int32_t>(n);
  }
  int32_t const need = veloxPolygonBlobSize(numParts, numPoints);
  if (outSize < need) {
    markInvalid(invalidTypeFlag);
    return false;
  }

  out[0] = static_cast<char>(kPolygonTag);
  writeI32Native(out + 1, kEsriPolygon);
  writeI32Native(out + 37, numParts);
  writeI32Native(out + 41, numPoints);

  char* partPtr = out + kEmptyPolygonBlobSize;
  char* xyPtr = partPtr + 4 * numParts;
  double xmin = INFINITY;
  double ymin = INFINITY;
  double xmax = -INFINITY;
  double ymax = -INFINITY;

  off = body + 4;
  int32_t pointIdx = 0;
  for (int32_t r = 0; r < numParts; ++r) {
    writeI32Native(partPtr + 4 * r, pointIdx);
    uint32_t const n = readU32(wkb + off, le);
    off += 4;
    for (uint32_t i = 0; i < n; ++i) {
      double const x = readF64(wkb + off, le);
      double const y = readF64(wkb + off + 8, le);
      off += 16;
      xmin = fmin(xmin, x);
      ymin = fmin(ymin, y);
      xmax = fmax(xmax, x);
      ymax = fmax(ymax, y);
      writeF64Native(xyPtr + static_cast<std::size_t>(pointIdx) * 16, x);
      writeF64Native(xyPtr + static_cast<std::size_t>(pointIdx) * 16 + 8, y);
      ++pointIdx;
    }
  }
  writeF64Native(out + 5, xmin);
  writeF64Native(out + 13, ymin);
  writeF64Native(out + 21, xmax);
  writeF64Native(out + 29, ymax);
  return true;
}

} // namespace

std::unique_ptr<cudf::column> extractPointCoordinate(
    cudf::column_view const& geometry,
    bool extractY,
    int32_t* invalidTypeFlag,
    rmm::cuda_stream_view stream,
    rmm::device_async_resource_ref mr) {
  CUDF_EXPECTS(
      geometry.type().id() == cudf::type_id::STRING,
      "geometry input must be STRING/VARBINARY");

  cudf::strings_column_view strings(geometry);
  auto const size = geometry.size();
  auto out = cudf::make_numeric_column(
      cudf::data_type{cudf::type_id::FLOAT64},
      size,
      cudf::mask_state::ALL_VALID,
      stream,
      mr);
  auto* outPtr = out->mutable_view().data<double>();
  auto outMask = static_cast<cudf::bitmask_type*>(out->mutable_view().null_mask());

  auto chars = strings.chars_begin(stream);
  auto offsets = strings.offsets().begin<cudf::size_type>();
  auto inNull = geometry.null_mask();

  thrust::for_each_n(
      rmm::exec_policy(stream),
      thrust::counting_iterator<cudf::size_type>(0),
      size,
      [chars,
       offsets,
       inNull,
       outPtr,
       outMask,
       extractY,
       invalidTypeFlag,
       nullCount = geometry.null_count()] __device__(cudf::size_type i) {
        if (nullCount > 0 && inNull != nullptr &&
            !cudf::bit_is_set(inNull, i)) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        auto const start = offsets[i];
        auto const end = offsets[i + 1];
        double x = 0;
        double y = 0;
        if (!readPointXY(chars + start, end - start, x, y, invalidTypeFlag)) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        if (isEmptyPoint(x, y)) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        outPtr[i] = extractY ? y : x;
      });

  out->set_null_count(
      cudf::null_count(out->view().null_mask(), 0, size, stream));
  return out;
}

std::unique_ptr<cudf::column> pointPointDistance(
    cudf::column_view const& left,
    cudf::column_view const& right,
    int32_t* invalidTypeFlag,
    rmm::cuda_stream_view stream,
    rmm::device_async_resource_ref mr) {
  CUDF_EXPECTS(
      left.type().id() == cudf::type_id::STRING &&
          right.type().id() == cudf::type_id::STRING,
      "geometry inputs must be STRING/VARBINARY");
  CUDF_EXPECTS(left.size() == right.size(), "geometry size mismatch");

  cudf::strings_column_view leftStr(left);
  cudf::strings_column_view rightStr(right);
  auto const size = left.size();
  auto out = cudf::make_numeric_column(
      cudf::data_type{cudf::type_id::FLOAT64},
      size,
      cudf::mask_state::ALL_VALID,
      stream,
      mr);
  auto outMask =
      static_cast<cudf::bitmask_type*>(out->mutable_view().null_mask());

  // Parse Velox POINT blobs into cuSpatial vec_2d coordinate arrays. This
  // marshalling step is Velox-serialization-specific and has no cuSpatial
  // equivalent; the actual Cartesian distance *kernel* below is cuSpatial's
  // (cuspatial::pairwise_point_distance), not a hand-rolled formula.
  rmm::device_uvector<cuspatial::vec_2d<double>> leftPts(size, stream, mr);
  rmm::device_uvector<cuspatial::vec_2d<double>> rightPts(size, stream, mr);
  auto* leftPtsPtr = leftPts.data();
  auto* rightPtsPtr = rightPts.data();

  auto leftChars = leftStr.chars_begin(stream);
  auto rightChars = rightStr.chars_begin(stream);
  auto leftOffsets = leftStr.offsets().begin<cudf::size_type>();
  auto rightOffsets = rightStr.offsets().begin<cudf::size_type>();
  auto leftNull = left.null_mask();
  auto rightNull = right.null_mask();

  thrust::for_each_n(
      rmm::exec_policy(stream),
      thrust::counting_iterator<cudf::size_type>(0),
      size,
      [leftChars,
       rightChars,
       leftOffsets,
       rightOffsets,
       leftNull,
       rightNull,
       leftPtsPtr,
       rightPtsPtr,
       outMask,
       invalidTypeFlag,
       leftNullCount = left.null_count(),
       rightNullCount = right.null_count()] __device__(cudf::size_type i) {
        // Fill with a well-defined value even on the invalid path; the
        // output row is masked null regardless, so the value is never
        // observed, but cuSpatial's kernel still reads every row.
        leftPtsPtr[i] = {0.0, 0.0};
        rightPtsPtr[i] = {0.0, 0.0};
        if ((leftNullCount > 0 && leftNull != nullptr &&
             !cudf::bit_is_set(leftNull, i)) ||
            (rightNullCount > 0 && rightNull != nullptr &&
             !cudf::bit_is_set(rightNull, i))) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        double x1 = 0, y1 = 0, x2 = 0, y2 = 0;
        auto const ls = leftOffsets[i];
        auto const le = leftOffsets[i + 1];
        auto const rs = rightOffsets[i];
        auto const re = rightOffsets[i + 1];
        if (!readPointXY(leftChars + ls, le - ls, x1, y1, invalidTypeFlag) ||
            !readPointXY(rightChars + rs, re - rs, x2, y2, invalidTypeFlag)) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        if (isEmptyPoint(x1, y1) || isEmptyPoint(x2, y2)) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        leftPtsPtr[i] = {x1, y1};
        rightPtsPtr[i] = {x2, y2};
      });

  // cuSpatial's pairwise point-to-point Cartesian distance kernel. Each row
  // is its own single-point "multipoint" (identity geometry offsets: point
  // i is multipoint i's only point), matching the row-wise ST_Distance
  // semantics above.
  auto const offsetIt = thrust::counting_iterator<int64_t>(0);
  auto leftRange = cuspatial::make_multipoint_range(
      static_cast<int64_t>(size),
      offsetIt,
      static_cast<int64_t>(size),
      leftPts.begin());
  auto rightRange = cuspatial::make_multipoint_range(
      static_cast<int64_t>(size),
      offsetIt,
      static_cast<int64_t>(size),
      rightPts.begin());
  cuspatial::pairwise_point_distance(
      leftRange, rightRange, out->mutable_view().data<double>(), stream);

  out->set_null_count(
      cudf::null_count(out->view().null_mask(), 0, size, stream));
  return out;
}

std::unique_ptr<cudf::column> makePointGeometry(
    cudf::column_view const& x,
    cudf::column_view const& y,
    rmm::cuda_stream_view stream,
    rmm::device_async_resource_ref mr) {
  CUDF_EXPECTS(
      x.type().id() == cudf::type_id::FLOAT64 &&
          y.type().id() == cudf::type_id::FLOAT64,
      "ST_Point expects double coordinates");
  CUDF_EXPECTS(x.size() == y.size(), "ST_Point size mismatch");

  auto const size = x.size();
  // offsets: size+1 entries, each row is exactly kPointBlobSize bytes.
  auto offsetsCol = cudf::make_numeric_column(
      cudf::data_type{cudf::type_id::INT32},
      size + 1,
      cudf::mask_state::UNALLOCATED,
      stream,
      mr);
  auto* offsets = offsetsCol->mutable_view().data<cudf::size_type>();
  thrust::for_each_n(
      rmm::exec_policy(stream),
      thrust::counting_iterator<cudf::size_type>(0),
      size + 1,
      [offsets] __device__(cudf::size_type i) {
        offsets[i] = i * kPointBlobSize;
      });

  rmm::device_uvector<char> chars(
      static_cast<std::size_t>(size) * kPointBlobSize, stream, mr);
  auto* charsPtr = chars.data();
  auto const* xPtr = x.data<double>();
  auto const* yPtr = y.data<double>();
  auto xNull = x.null_mask();
  auto yNull = y.null_mask();

  // Output null mask: null if either input is null.
  auto [nullMask, nullCount] =
      cudf::bitmask_and(cudf::table_view{{x, y}}, stream, mr);

  thrust::for_each_n(
      rmm::exec_policy(stream),
      thrust::counting_iterator<cudf::size_type>(0),
      size,
      [charsPtr,
       xPtr,
       yPtr,
       xNull,
       yNull,
       xNullCount = x.null_count(),
       yNullCount = y.null_count()] __device__(cudf::size_type i) {
        if ((xNullCount > 0 && xNull != nullptr &&
             !cudf::bit_is_set(xNull, i)) ||
            (yNullCount > 0 && yNull != nullptr &&
             !cudf::bit_is_set(yNull, i))) {
          return;
        }
        double xv = xPtr[i];
        double yv = yPtr[i];
        char* row = charsPtr + static_cast<std::size_t>(i) * kPointBlobSize;
        row[0] = static_cast<char>(kPointTag);
        auto const* xb = reinterpret_cast<char const*>(&xv);
        auto const* yb = reinterpret_cast<char const*>(&yv);
#pragma unroll
        for (int b = 0; b < 8; ++b) {
          row[1 + b] = xb[b];
          row[9 + b] = yb[b];
        }
      });

  return cudf::make_strings_column(
      size,
      std::move(offsetsCol),
      chars.release(),
      nullCount,
      std::move(nullMask));
}

std::unique_ptr<cudf::column> wkbToVeloxGeometry(
    cudf::column_view const& wkb,
    int32_t* invalidTypeFlag,
    rmm::cuda_stream_view stream,
    rmm::device_async_resource_ref mr) {
  CUDF_EXPECTS(
      wkb.type().id() == cudf::type_id::STRING,
      "ST_GeomFromBinary expects VARBINARY/STRING WKB");

  cudf::strings_column_view strings(wkb);
  auto const size = wkb.size();

  auto inChars = strings.chars_begin(stream);
  auto inOffsets = strings.offsets().begin<cudf::size_type>();
  auto inNull = wkb.null_mask();

  auto [nullMaskBuf, nullCountHint] = [&]() {
    if (wkb.null_mask() != nullptr) {
      auto buf = cudf::copy_bitmask(wkb, stream, mr);
      return std::make_pair(std::move(buf), wkb.null_count());
    }
    return std::make_pair(
        cudf::create_null_mask(size, cudf::mask_state::ALL_VALID, stream, mr),
        0);
  }();
  auto* outMask = static_cast<cudf::bitmask_type*>(nullMaskBuf.data());

  // sizes[0..size-1] = blob bytes; sizes[size]=0 for exclusive_scan → offsets.
  rmm::device_uvector<cudf::size_type> sizes(size + 1, stream, mr);
  auto* sizesPtr = sizes.data();
  thrust::for_each_n(
      rmm::exec_policy(stream),
      thrust::counting_iterator<cudf::size_type>(0),
      size + 1,
      [sizesPtr,
       inChars,
       inOffsets,
       inNull,
       outMask,
       invalidTypeFlag,
       size,
       inNullCount = wkb.null_count()] __device__(cudf::size_type i) {
        if (i == size) {
          sizesPtr[i] = 0;
          return;
        }
        if (inNullCount > 0 && inNull != nullptr &&
            !cudf::bit_is_set(inNull, i)) {
          sizesPtr[i] = 0;
          return;
        }
        int32_t blobSize = 0;
        auto const start = inOffsets[i];
        auto const end = inOffsets[i + 1];
        if (!wkbVeloxOutputSize(
                inChars + start, end - start, &blobSize, invalidTypeFlag)) {
          sizesPtr[i] = 0;
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        sizesPtr[i] = static_cast<cudf::size_type>(blobSize);
      });

  auto offsetsCol = cudf::make_numeric_column(
      cudf::data_type{cudf::type_id::INT32},
      size + 1,
      cudf::mask_state::UNALLOCATED,
      stream,
      mr);
  auto* offsets = offsetsCol->mutable_view().data<cudf::size_type>();
  thrust::exclusive_scan(
      rmm::exec_policy(stream),
      sizes.begin(),
      sizes.end(),
      offsets);

  cudf::size_type totalChars = 0;
  CUDF_CUDA_TRY(cudaMemcpyAsync(
      &totalChars,
      offsets + size,
      sizeof(cudf::size_type),
      cudaMemcpyDeviceToHost,
      stream.value()));
  stream.synchronize();

  rmm::device_uvector<char> chars(
      static_cast<std::size_t>(totalChars), stream, mr);
  auto* charsPtr = chars.data();

  thrust::for_each_n(
      rmm::exec_policy(stream),
      thrust::counting_iterator<cudf::size_type>(0),
      size,
      [charsPtr,
       offsets,
       inChars,
       inOffsets,
       inNull,
       outMask,
       invalidTypeFlag,
       inNullCount = wkb.null_count()] __device__(cudf::size_type i) {
        if (inNullCount > 0 && inNull != nullptr &&
            !cudf::bit_is_set(inNull, i)) {
          return;
        }
        if (!cudf::bit_is_set(outMask, i)) {
          return;
        }
        auto const outStart = offsets[i];
        auto const outEnd = offsets[i + 1];
        auto const outLen = outEnd - outStart;
        if (outLen <= 0) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        auto const start = inOffsets[i];
        auto const end = inOffsets[i + 1];
        if (!wkbToVeloxBlob(
                inChars + start,
                end - start,
                charsPtr + outStart,
                outLen,
                invalidTypeFlag)) {
          cudf::clear_bit_unsafe(outMask, i);
        }
      });

  auto nullCount = cudf::null_count(
      static_cast<cudf::bitmask_type const*>(nullMaskBuf.data()),
      0,
      size,
      stream);
  return cudf::make_strings_column(
      size,
      std::move(offsetsCol),
      chars.release(),
      nullCount,
      std::move(nullMaskBuf));
}

namespace {

template <typename T>
T readPod(char const*& p, char const* end) {
  if (p + sizeof(T) > end) {
    throw std::runtime_error("Truncated Velox geometry blob");
  }
  T v;
  std::memcpy(&v, p, sizeof(T));
  p += sizeof(T);
  return v;
}

} // namespace

bool parseVeloxPolygon(
    std::string_view geometry,
    std::vector<double>& xyOut,
    std::vector<int32_t>& partEndsOut) {
  xyOut.clear();
  partEndsOut.clear();
  if (geometry.empty()) {
    return false;
  }
  char const* p = geometry.data();
  char const* end = p + geometry.size();
  auto tag = static_cast<uint8_t>(readPod<char>(p, end));

  constexpr uint8_t kPolygonTag = 4;
  constexpr uint8_t kEnvelopeTag = 7;

  if (tag == kEnvelopeTag) {
    double xmin = readPod<double>(p, end);
    double ymin = readPod<double>(p, end);
    double xmax = readPod<double>(p, end);
    double ymax = readPod<double>(p, end);
    if (std::isnan(xmin) || std::isnan(ymin) || std::isnan(xmax) ||
        std::isnan(ymax)) {
      return false;
    }
    // Closed rectangle ring.
    xyOut = {
        xmin, ymin, xmax, ymin, xmax, ymax, xmin, ymax, xmin, ymin};
    partEndsOut = {5};
    return true;
  }

  if (tag != kPolygonTag) {
    return false;
  }
  // Skip Esri type + envelope.
  (void)readPod<int32_t>(p, end);
  (void)readPod<double>(p, end);
  (void)readPod<double>(p, end);
  (void)readPod<double>(p, end);
  (void)readPod<double>(p, end);

  int32_t numParts = readPod<int32_t>(p, end);
  int32_t numPoints = readPod<int32_t>(p, end);
  if (numParts <= 0 || numPoints <= 0) {
    return false;
  }
  std::vector<int32_t> starts(static_cast<size_t>(numParts));
  for (int32_t i = 0; i < numParts; ++i) {
    starts[static_cast<size_t>(i)] = readPod<int32_t>(p, end);
  }
  partEndsOut.resize(static_cast<size_t>(numParts));
  for (int32_t i = 0; i < numParts - 1; ++i) {
    partEndsOut[static_cast<size_t>(i)] = starts[static_cast<size_t>(i + 1)];
  }
  partEndsOut[static_cast<size_t>(numParts - 1)] = numPoints;

  xyOut.resize(static_cast<size_t>(numPoints) * 2);
  for (int32_t i = 0; i < numPoints; ++i) {
    xyOut[static_cast<size_t>(2 * i)] = readPod<double>(p, end);
    xyOut[static_cast<size_t>(2 * i + 1)] = readPod<double>(p, end);
  }
  return true;
}

std::unique_ptr<cudf::column> pointToConstantPolygonDistance(
    cudf::column_view const& points,
    DevicePolygonView polygon,
    int32_t* invalidTypeFlag,
    rmm::cuda_stream_view stream,
    rmm::device_async_resource_ref mr) {
  CUDF_EXPECTS(
      points.type().id() == cudf::type_id::STRING,
      "points must be STRING/VARBINARY geometry");
  CUDF_EXPECTS(polygon.numParts > 0 && polygon.numPoints > 0, "empty polygon");
  CUDF_EXPECTS(
      polygon.xy != nullptr && polygon.partEnds != nullptr,
      "polygon device buffers required");

  cudf::strings_column_view strings(points);
  auto const size = points.size();
  auto out = cudf::make_numeric_column(
      cudf::data_type{cudf::type_id::FLOAT64},
      size,
      cudf::mask_state::ALL_VALID,
      stream,
      mr);
  auto outMask =
      static_cast<cudf::bitmask_type*>(out->mutable_view().null_mask());

  // Parse Velox POINT blobs into a cuSpatial vec_2d array. Velox-format
  // marshalling only; the point-vs-polygon distance *kernel* below is
  // cuSpatial's (cuspatial::pairwise_point_polygon_distance), replacing the
  // hand-rolled point-in-ring / min-dist-to-ring loop this used to be.
  rmm::device_uvector<cuspatial::vec_2d<double>> pts(size, stream, mr);
  auto* ptsPtr = pts.data();

  auto chars = strings.chars_begin(stream);
  auto offsets = strings.offsets().begin<cudf::size_type>();
  auto inNull = points.null_mask();

  thrust::for_each_n(
      rmm::exec_policy(stream),
      thrust::counting_iterator<cudf::size_type>(0),
      size,
      [chars,
       offsets,
       inNull,
       outMask,
       invalidTypeFlag,
       ptsPtr,
       nullCount = points.null_count()] __device__(cudf::size_type i) {
        ptsPtr[i] = {0.0, 0.0};
        if (nullCount > 0 && inNull != nullptr &&
            !cudf::bit_is_set(inNull, i)) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        double px = 0;
        double py = 0;
        auto const start = offsets[i];
        auto const end = offsets[i + 1];
        if (!readPointXY(chars + start, end - start, px, py, invalidTypeFlag)) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        if (isEmptyPoint(px, py)) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        ptsPtr[i] = {px, py};
      });

  // Broadcast the single constant polygon across `size` pairwise slots
  // using virtual (computed) offset/point iterators, so cuSpatial's
  // ragged-array multipolygon_range can be built without physically
  // replicating the (small) polygon ring data `size` times:
  //  - geometry_offsets: identity (each of the `size` multipolygons has
  //    exactly 1 polygon/"part" -- the constant polygon).
  //  - part_offsets: replica i's single part occupies ring slots
  //    [i*numParts, (i+1)*numParts) -- i.e. its own copy of the polygon's
  //    numParts rings (shell + holes).
  //  - ring_offsets: strictly monotonic *absolute* point indices
  //    (replica*numPoints + localOffset), so the flat CSR structure
  //    cuSpatial expects stays valid across replicas, even though...
  //  - the point iterator maps any absolute index back to the physical,
  //    unreplicated `polygon.xy` buffer via `% numPoints`.
  // Net effect: O(size) of *offsets* (small integers) are materialized,
  // never O(size * numPoints) of coordinate data.
  auto const numParts = polygon.numParts;
  auto const numPoints = polygon.numPoints;
  auto const* polyXy = polygon.xy;
  auto const* polyPartEnds = polygon.partEnds;

  auto const ptOffsetIt = thrust::counting_iterator<int64_t>(0);
  auto multipointRange = cuspatial::make_multipoint_range(
      static_cast<int64_t>(size),
      ptOffsetIt,
      static_cast<int64_t>(size),
      pts.begin());

  auto const geometryOffsetIt = thrust::counting_iterator<int64_t>(0);
  auto partOffsetIt = thrust::make_transform_iterator(
      thrust::counting_iterator<int64_t>(0),
      [numParts] __host__ __device__(int64_t i) -> int64_t {
        return i * numParts;
      });
  auto ringOffsetIt = thrust::make_transform_iterator(
      thrust::counting_iterator<int64_t>(0),
      [numPoints, numParts, polyPartEnds] __host__ __device__(
          int64_t globalRingIdx) -> int64_t {
        auto const replica = globalRingIdx / numParts;
        auto const ringInPoly = static_cast<int32_t>(globalRingIdx % numParts);
        auto const localStart =
            ringInPoly == 0 ? 0 : polyPartEnds[ringInPoly - 1];
        return replica * static_cast<int64_t>(numPoints) + localStart;
      });
  auto pointIt = thrust::make_transform_iterator(
      thrust::counting_iterator<int64_t>(0),
      [polyXy, numPoints] __host__ __device__(
          int64_t absoluteIdx) -> cuspatial::vec_2d<double> {
        auto const localIdx = absoluteIdx % numPoints;
        return cuspatial::vec_2d<double>{
            polyXy[2 * localIdx], polyXy[2 * localIdx + 1]};
      });

  auto multipolygonRange = cuspatial::multipolygon_range(
      geometryOffsetIt,
      geometryOffsetIt + size + 1,
      partOffsetIt,
      partOffsetIt + size + 1,
      ringOffsetIt,
      ringOffsetIt + static_cast<int64_t>(size) * numParts + 1,
      pointIt,
      pointIt + static_cast<int64_t>(size) * numPoints);

  cuspatial::pairwise_point_polygon_distance(
      multipointRange,
      multipolygonRange,
      out->mutable_view().data<double>(),
      stream);

  out->set_null_count(
      cudf::null_count(out->view().null_mask(), 0, size, stream));
  return out;
}

std::unique_ptr<cudf::column> geometryDistance(
    cudf::column_view const& left,
    cudf::column_view const& right,
    int32_t* invalidTypeFlag,
    rmm::cuda_stream_view stream,
    rmm::device_async_resource_ref mr) {
  CUDF_EXPECTS(
      left.type().id() == cudf::type_id::STRING &&
          right.type().id() == cudf::type_id::STRING,
      "geometry inputs must be STRING/VARBINARY");
  CUDF_EXPECTS(left.size() == right.size(), "geometry size mismatch");

  cudf::strings_column_view leftStr(left);
  cudf::strings_column_view rightStr(right);
  auto const size = left.size();
  auto out = cudf::make_numeric_column(
      cudf::data_type{cudf::type_id::FLOAT64},
      size,
      cudf::mask_state::ALL_VALID,
      stream,
      mr);
  auto* outPtr = out->mutable_view().data<double>();
  auto outMask =
      static_cast<cudf::bitmask_type*>(out->mutable_view().null_mask());

  auto leftChars = leftStr.chars_begin(stream);
  auto rightChars = rightStr.chars_begin(stream);
  auto leftOffsets = leftStr.offsets().begin<cudf::size_type>();
  auto rightOffsets = rightStr.offsets().begin<cudf::size_type>();
  auto leftNull = left.null_mask();
  auto rightNull = right.null_mask();

  thrust::for_each_n(
      rmm::exec_policy(stream),
      thrust::counting_iterator<cudf::size_type>(0),
      size,
      [leftChars,
       rightChars,
       leftOffsets,
       rightOffsets,
       leftNull,
       rightNull,
       outPtr,
       outMask,
       invalidTypeFlag,
       leftNullCount = left.null_count(),
       rightNullCount = right.null_count()] __device__(cudf::size_type i) {
        if ((leftNullCount > 0 && leftNull != nullptr &&
             !cudf::bit_is_set(leftNull, i)) ||
            (rightNullCount > 0 && rightNull != nullptr &&
             !cudf::bit_is_set(rightNull, i))) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        auto const ls = leftOffsets[i];
        auto const le = leftOffsets[i + 1];
        auto const rs = rightOffsets[i];
        auto const re = rightOffsets[i + 1];
        char const* leftData = leftChars + ls;
        char const* rightData = rightChars + rs;
        auto const leftLen = le - ls;
        auto const rightLen = re - rs;
        if (leftLen < 1 || rightLen < 1) {
          markInvalid(invalidTypeFlag);
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        uint8_t const leftTag = static_cast<uint8_t>(leftData[0]);
        uint8_t const rightTag = static_cast<uint8_t>(rightData[0]);

        // POINT–POINT
        if (leftTag == kPointTag && rightTag == kPointTag) {
          double x1 = 0, y1 = 0, x2 = 0, y2 = 0;
          if (!readPointXY(leftData, leftLen, x1, y1, invalidTypeFlag) ||
              !readPointXY(rightData, rightLen, x2, y2, invalidTypeFlag)) {
            cudf::clear_bit_unsafe(outMask, i);
            return;
          }
          if (isEmptyPoint(x1, y1) || isEmptyPoint(x2, y2)) {
            cudf::clear_bit_unsafe(outMask, i);
            return;
          }
          double const dx = x1 - x2;
          double const dy = y1 - y2;
          outPtr[i] = sqrt(dx * dx + dy * dy);
          return;
        }

        // POINT–POLYGON / ENVELOPE (either order)
        bool leftIsPoint = leftTag == kPointTag;
        bool rightIsPoly =
            rightTag == kPolygonTag || rightTag == kEnvelopeTag;
        bool rightIsPoint = rightTag == kPointTag;
        bool leftIsPoly = leftTag == kPolygonTag || leftTag == kEnvelopeTag;

        double px = 0;
        double py = 0;
        char const* polyData = nullptr;
        cudf::size_type polyLen = 0;
        if (leftIsPoint && rightIsPoly) {
          if (!readPointXY(leftData, leftLen, px, py, invalidTypeFlag)) {
            cudf::clear_bit_unsafe(outMask, i);
            return;
          }
          polyData = rightData;
          polyLen = rightLen;
        } else if (leftIsPoly && rightIsPoint) {
          if (!readPointXY(rightData, rightLen, px, py, invalidTypeFlag)) {
            cudf::clear_bit_unsafe(outMask, i);
            return;
          }
          polyData = leftData;
          polyLen = leftLen;
        } else {
          markInvalid(invalidTypeFlag);
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        if (isEmptyPoint(px, py)) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        double dist = 0;
        if (!distPointToPolygonBlob(
                px, py, polyData, polyLen, dist, invalidTypeFlag)) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        outPtr[i] = dist;
      });

  out->set_null_count(
      cudf::null_count(out->view().null_mask(), 0, size, stream));
  return out;
}

std::unique_ptr<cudf::column> makeLineStringFromPointList(
    cudf::column_view const& pointLists,
    int32_t* invalidTypeFlag,
    rmm::cuda_stream_view stream,
    rmm::device_async_resource_ref mr) {
  CUDF_EXPECTS(
      pointLists.type().id() == cudf::type_id::LIST,
      "ST_LineString expects array(geometry)");

  cudf::lists_column_view lists(pointLists);
  auto const size = pointLists.size();
  auto points = lists.get_sliced_child(stream);
  CUDF_EXPECTS(
      points.type().id() == cudf::type_id::STRING,
      "ST_LineString array elements must be geometry/STRING");

  cudf::strings_column_view pointStrings(points);
  auto pointChars = pointStrings.chars_begin(stream);
  auto pointOffsets = pointStrings.offsets().begin<cudf::size_type>();
  auto pointNull = points.null_mask();
  auto listOffsets = lists.offsets().begin<cudf::size_type>();
  auto listNull = pointLists.null_mask();

  auto [nullMaskBuf, nullCountHint] = [&]() {
    if (pointLists.null_mask() != nullptr) {
      auto buf = cudf::copy_bitmask(pointLists, stream, mr);
      return std::make_pair(std::move(buf), pointLists.null_count());
    }
    return std::make_pair(
        cudf::create_null_mask(size, cudf::mask_state::ALL_VALID, stream, mr),
        0);
  }();
  (void)nullCountHint;
  auto* outMask = static_cast<cudf::bitmask_type*>(nullMaskBuf.data());

  rmm::device_uvector<cudf::size_type> sizes(size + 1, stream, mr);
  auto* sizesPtr = sizes.data();

  thrust::for_each_n(
      rmm::exec_policy(stream),
      thrust::counting_iterator<cudf::size_type>(0),
      size + 1,
      [sizesPtr,
       listOffsets,
       listNull,
       pointOffsets,
       pointChars,
       pointNull,
       outMask,
       invalidTypeFlag,
       size,
       listNullCount = pointLists.null_count(),
       pointNullCount = points.null_count()] __device__(cudf::size_type i) {
        if (i == size) {
          sizesPtr[i] = 0;
          return;
        }
        if (listNullCount > 0 && listNull != nullptr &&
            !cudf::bit_is_set(listNull, i)) {
          sizesPtr[i] = 0;
          return;
        }
        auto const begin = listOffsets[i];
        auto const end = listOffsets[i + 1];
        auto const n = end - begin;
        if (n < 2) {
          sizesPtr[i] = kEmptyLineStringBlobSize;
          return;
        }
        // Validate points; size the blob.
        for (cudf::size_type j = begin; j < end; ++j) {
          if (pointNullCount > 0 && pointNull != nullptr &&
              !cudf::bit_is_set(pointNull, j)) {
            markInvalid(invalidTypeFlag);
            sizesPtr[i] = 0;
            cudf::clear_bit_unsafe(outMask, i);
            return;
          }
          double x = 0;
          double y = 0;
          auto const ps = pointOffsets[j];
          auto const pe = pointOffsets[j + 1];
          if (!readPointXY(pointChars + ps, pe - ps, x, y, invalidTypeFlag)) {
            sizesPtr[i] = 0;
            cudf::clear_bit_unsafe(outMask, i);
            return;
          }
          if (isEmptyPoint(x, y)) {
            markInvalid(invalidTypeFlag);
            sizesPtr[i] = 0;
            cudf::clear_bit_unsafe(outMask, i);
            return;
          }
          // Consecutive duplicates allowed (Sedona ST_MakeLine / Q7 parity).
        }
        sizesPtr[i] = static_cast<cudf::size_type>(
            veloxLineStringBlobSize(static_cast<int32_t>(n)));
      });

  auto offsetsCol = cudf::make_numeric_column(
      cudf::data_type{cudf::type_id::INT32},
      size + 1,
      cudf::mask_state::UNALLOCATED,
      stream,
      mr);
  auto* offsets = offsetsCol->mutable_view().data<cudf::size_type>();
  thrust::exclusive_scan(
      rmm::exec_policy(stream), sizes.begin(), sizes.end(), offsets);

  cudf::size_type totalChars = 0;
  CUDF_CUDA_TRY(cudaMemcpyAsync(
      &totalChars,
      offsets + size,
      sizeof(cudf::size_type),
      cudaMemcpyDeviceToHost,
      stream.value()));
  stream.synchronize();

  rmm::device_uvector<char> chars(
      static_cast<std::size_t>(totalChars), stream, mr);
  auto* charsPtr = chars.data();

  thrust::for_each_n(
      rmm::exec_policy(stream),
      thrust::counting_iterator<cudf::size_type>(0),
      size,
      [charsPtr,
       offsets,
       listOffsets,
       listNull,
       pointOffsets,
       pointChars,
       pointNull,
       outMask,
       invalidTypeFlag,
       listNullCount = pointLists.null_count(),
       pointNullCount = points.null_count()] __device__(cudf::size_type i) {
        if (listNullCount > 0 && listNull != nullptr &&
            !cudf::bit_is_set(listNull, i)) {
          return;
        }
        if (!cudf::bit_is_set(outMask, i)) {
          return;
        }
        auto const outStart = offsets[i];
        auto const outEnd = offsets[i + 1];
        auto const outLen = outEnd - outStart;
        if (outLen <= 0) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        char* out = charsPtr + outStart;
        auto const begin = listOffsets[i];
        auto const end = listOffsets[i + 1];
        auto const n = end - begin;

        if (n < 2) {
          // Empty LINESTRING.
          out[0] = static_cast<char>(kLineStringTag);
          writeI32Native(out + 1, kEsriPolyline);
          double const nan = NAN;
          writeF64Native(out + 5, nan);
          writeF64Native(out + 13, nan);
          writeF64Native(out + 21, nan);
          writeF64Native(out + 29, nan);
          writeI32Native(out + 37, 0);
          writeI32Native(out + 41, 0);
          return;
        }

        out[0] = static_cast<char>(kLineStringTag);
        writeI32Native(out + 1, kEsriPolyline);
        writeI32Native(out + 37, 1); // numParts
        writeI32Native(out + 41, static_cast<int32_t>(n));
        writeI32Native(out + 45, 0); // partStarts[0]
        char* xyPtr = out + 49;

        double xmin = INFINITY;
        double ymin = INFINITY;
        double xmax = -INFINITY;
        double ymax = -INFINITY;
        int32_t pointIdx = 0;
        for (cudf::size_type j = begin; j < end; ++j) {
          double x = 0;
          double y = 0;
          auto const ps = pointOffsets[j];
          auto const pe = pointOffsets[j + 1];
          if (!readPointXY(pointChars + ps, pe - ps, x, y, invalidTypeFlag)) {
            cudf::clear_bit_unsafe(outMask, i);
            return;
          }
          xmin = fmin(xmin, x);
          ymin = fmin(ymin, y);
          xmax = fmax(xmax, x);
          ymax = fmax(ymax, y);
          writeF64Native(xyPtr + static_cast<std::size_t>(pointIdx) * 16, x);
          writeF64Native(
              xyPtr + static_cast<std::size_t>(pointIdx) * 16 + 8, y);
          ++pointIdx;
        }
        writeF64Native(out + 5, xmin);
        writeF64Native(out + 13, ymin);
        writeF64Native(out + 21, xmax);
        writeF64Native(out + 29, ymax);
      });

  auto nullCount = cudf::null_count(
      static_cast<cudf::bitmask_type const*>(nullMaskBuf.data()),
      0,
      size,
      stream);
  return cudf::make_strings_column(
      size,
      std::move(offsetsCol),
      chars.release(),
      nullCount,
      std::move(nullMaskBuf));
}

std::unique_ptr<cudf::column> lineStringLength(
    cudf::column_view const& geometry,
    int32_t* invalidTypeFlag,
    rmm::cuda_stream_view stream,
    rmm::device_async_resource_ref mr) {
  CUDF_EXPECTS(
      geometry.type().id() == cudf::type_id::STRING,
      "ST_Length expects geometry/STRING");

  cudf::strings_column_view strings(geometry);
  auto const size = geometry.size();
  auto out = cudf::make_numeric_column(
      cudf::data_type{cudf::type_id::FLOAT64},
      size,
      cudf::mask_state::ALL_VALID,
      stream,
      mr);
  auto* outPtr = out->mutable_view().data<double>();
  auto outMask =
      static_cast<cudf::bitmask_type*>(out->mutable_view().null_mask());

  auto chars = strings.chars_begin(stream);
  auto offsets = strings.offsets().begin<cudf::size_type>();
  auto inNull = geometry.null_mask();

  thrust::for_each_n(
      rmm::exec_policy(stream),
      thrust::counting_iterator<cudf::size_type>(0),
      size,
      [chars,
       offsets,
       inNull,
       outPtr,
       outMask,
       invalidTypeFlag,
       nullCount = geometry.null_count()] __device__(cudf::size_type i) {
        if (nullCount > 0 && inNull != nullptr &&
            !cudf::bit_is_set(inNull, i)) {
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        auto const start = offsets[i];
        auto const end = offsets[i + 1];
        auto const len = end - start;
        char const* data = chars + start;
        if (len < kEmptyLineStringBlobSize) {
          markInvalid(invalidTypeFlag);
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        uint8_t const tag = static_cast<uint8_t>(data[0]);
        if (tag != kLineStringTag && tag != kMultiLineStringTag) {
          markInvalid(invalidTypeFlag);
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        int32_t const numParts = readI32Native(data + 37);
        int32_t const numPoints = readI32Native(data + 41);
        if (numParts <= 0 || numPoints <= 1) {
          outPtr[i] = 0.0;
          return;
        }
        std::size_t const partsBytes =
            static_cast<std::size_t>(numParts) * sizeof(int32_t);
        std::size_t const xyBytes =
            static_cast<std::size_t>(numPoints) * 16;
        if (static_cast<std::size_t>(len) <
            static_cast<std::size_t>(kEmptyLineStringBlobSize) + partsBytes +
                xyBytes) {
          markInvalid(invalidTypeFlag);
          cudf::clear_bit_unsafe(outMask, i);
          return;
        }
        char const* partPtr = data + kEmptyLineStringBlobSize;
        char const* xy = partPtr + partsBytes;

        double total = 0.0;
        for (int32_t p = 0; p < numParts; ++p) {
          int32_t const ps = readI32Native(
              partPtr + static_cast<std::size_t>(p) * 4);
          int32_t const pe = (p + 1 < numParts)
              ? readI32Native(
                    partPtr + static_cast<std::size_t>(p + 1) * 4)
              : numPoints;
          for (int32_t k = ps; k + 1 < pe; ++k) {
            double const x0 = xyBytesX(xy, k);
            double const y0 = xyBytesY(xy, k);
            double const x1 = xyBytesX(xy, k + 1);
            double const y1 = xyBytesY(xy, k + 1);
            double const dx = x1 - x0;
            double const dy = y1 - y0;
            total += sqrt(dx * dx + dy * dy);
          }
        }
        outPtr[i] = total;
      });

  out->set_null_count(
      cudf::null_count(out->view().null_mask(), 0, size, stream));
  return out;
}

std::unique_ptr<cudf::column> haversineGreatCircleDistance(
    cudf::column_view const& lat1,
    cudf::column_view const& lon1,
    cudf::column_view const& lat2,
    cudf::column_view const& lon2,
    double radiusKm,
    rmm::cuda_stream_view stream,
    rmm::device_async_resource_ref mr) {
  CUDF_EXPECTS(
      lat1.type().id() == cudf::type_id::FLOAT64 &&
          lon1.type().id() == cudf::type_id::FLOAT64 &&
          lat2.type().id() == cudf::type_id::FLOAT64 &&
          lon2.type().id() == cudf::type_id::FLOAT64,
      "great_circle_distance expects DOUBLE lat/lon columns");
  auto const size = lat1.size();
  CUDF_EXPECTS(
      lon1.size() == size && lat2.size() == size && lon2.size() == size,
      "great_circle_distance size mismatch");

  auto out = cudf::make_numeric_column(
      cudf::data_type{cudf::type_id::FLOAT64},
      size,
      cudf::mask_state::UNALLOCATED,
      stream,
      mr);

  auto const* lat1Ptr = lat1.data<double>();
  auto const* lon1Ptr = lon1.data<double>();
  auto const* lat2Ptr = lat2.data<double>();
  auto const* lon2Ptr = lon2.data<double>();

  // cuSpatial's haversine_distance expects (lon, lat) vec_2d iterators; it
  // is the same exact-sphere formula as the Vincenty/atan2 form this used
  // to compute by hand (both are exact great-circle-distance formulas for a
  // sphere, just different-but-equivalent trigonometric identities), so
  // results match to floating-point precision for non-antipodal points.
  auto aIt = thrust::make_transform_iterator(
      thrust::counting_iterator<cudf::size_type>(0),
      [lon1Ptr, lat1Ptr] __host__ __device__(
          cudf::size_type i) -> cuspatial::vec_2d<double> {
        return {lon1Ptr[i], lat1Ptr[i]};
      });
  auto bIt = thrust::make_transform_iterator(
      thrust::counting_iterator<cudf::size_type>(0),
      [lon2Ptr, lat2Ptr] __host__ __device__(
          cudf::size_type i) -> cuspatial::vec_2d<double> {
        return {lon2Ptr[i], lat2Ptr[i]};
      });

  cuspatial::haversine_distance(
      aIt,
      aIt + size,
      bIt,
      out->mutable_view().data<double>(),
      radiusKm,
      stream);

  if (lat1.nullable() || lon1.nullable() || lat2.nullable() ||
      lon2.nullable()) {
    auto [nullMask, nullCount] = cudf::bitmask_and(
        cudf::table_view{{lat1, lon1, lat2, lon2}}, stream, mr);
    out->set_null_mask(std::move(nullMask), nullCount);
  }
  return out;
}

} // namespace facebook::velox::cudf_velox
